require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '16.0'

use_frameworks! :linkage => :static
use_modular_headers!

prepare_react_native_project!

target 'FirebaseLiveChatApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config_build|

        # 🔥 Fix for Header Redefinition / Modular Errors
        if target.name.start_with?("RNFB")
          config_build.build_settings['CLANG_ENABLE_MODULES'] = 'NO'
        end

        config_build.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
        config_build.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'

        # 🔥 gRPC fix
        if target.name == 'gRPC-C++' || target.name == 'gRPC-Core'
          config_build.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
          config_build.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = 'NO'
          config_build.build_settings['CLANG_WARN_STRICT_PROTOTYPES'] = 'NO'
          config_build.build_settings['WARNING_CFLAGS'] = '-Wno-everything'
        end

      end
    end
  end
end